[package]
name = "otf2fontspec"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.32"
colored = "2.0.0"
opentype = "0.24.3"
regex = "1.7.1"
serde_json = "1.0.91"
